import type { ComplianceQuestion, ComplianceSectionId } from './types';

export const SECTION_LABELS: Record<ComplianceSectionId, string> = {
  people: 'People & Appointments',
  systems: 'Systems & Protocols',
  students: 'Student Support',
  records: 'Records & Reporting',
  training: 'Staff Training',
};

export const COMPLIANCE_QUESTIONS: ComplianceQuestion[] = [
  {
    id: 'Q1',
    order: 1,
    section: 'people',
    question: 'Does your school have at least one appointed counsellor, psychologist, or social worker dedicated to student wellbeing support?',
    shortTitle: 'No appointed wellbeing professional',
    regulatoryRef: 'SC Guideline II',
    legalRisk: 'Without a qualified support professional, institutions are directly non-compliant with the court-mandated baseline requirement.',
    zengardenCovers: 'Zengarden provides access to RCI-certified and MPhil psychologists through the platform without requiring a full-time hire.',
  },
  {
    id: 'Q2',
    order: 2,
    section: 'people',
    question: 'Is your counsellor qualified with recognised psychology or social work credentials that can be verified?',
    shortTitle: 'Counsellor credentials not verifiable',
    regulatoryRef: 'SC Guideline II · CBSE Qualification Requirement',
    legalRisk: 'Unverified credentials do not satisfy compliance expectations during regulatory review.',
    zengardenCovers: 'All Zengarden psychologists are profile-verified with visible credentials.',
  },
  {
    id: 'Q3',
    order: 3,
    section: 'people',
    cbseOnly: true,
    question: 'Do you have a dedicated Career Counsellor role that is separate from your wellness/socio-emotional counsellor role?',
    shortTitle: 'Separate career role missing',
    regulatoryRef: 'CBSE Clause 2.4.12.2',
    legalRisk: 'CBSE requires distinct counselling functions; combining roles may impact affiliation compliance.',
    zengardenCovers: 'Zengarden mentor pathways and role-based access support separate career counselling workflows.',
  },
  {
    id: 'Q4',
    order: 4,
    section: 'people',
    cbseOnly: true,
    question: 'Does your student-to-counsellor ratio meet the 1:500 requirement for Classes 9–12?',
    shortTitle: 'Counsellor ratio not met',
    regulatoryRef: 'CBSE Clause 2.4.12.1',
    legalRisk: 'Insufficient counsellor coverage is a recurring compliance gap during affiliation checks.',
    zengardenCovers: 'Zengarden gives access to multiple qualified professionals through one platform subscription.',
  },
  {
    id: 'Q5',
    order: 5,
    section: 'systems',
    question: 'Does your school have a written mental health and wellbeing policy that is publicly accessible?',
    shortTitle: 'No published wellbeing policy',
    regulatoryRef: 'SC Guideline I',
    legalRisk: 'Absence of a documented policy is a direct compliance exposure during inspections.',
    zengardenCovers: 'Zengarden provides structured digital infrastructure that supports formal policy implementation.',
  },
  {
    id: 'Q6',
    order: 6,
    section: 'systems',
    question: 'Does your school have a documented referral protocol for identifying and supporting distressed students?',
    shortTitle: 'Referral protocol undocumented',
    regulatoryRef: 'SC Guideline V',
    legalRisk: 'Informal referral practices are difficult to defend without documented process evidence.',
    zengardenCovers: 'Zengarden includes a documented flow from check-in to counsellor/psychologist escalation with logs.',
  },
  {
    id: 'Q7',
    order: 7,
    section: 'systems',
    question: 'Are national crisis helpline numbers (including Tele-MANAS 14416 and iCall) prominently displayed for students?',
    shortTitle: 'Crisis helplines not displayed',
    regulatoryRef: 'SC Guideline V',
    legalRisk: 'Missing helpline display is an auditable gap that can be flagged immediately.',
    zengardenCovers: 'Zengarden surfaces crisis resources and helpline references inside the student interface.',
  },
  {
    id: 'Q8',
    order: 8,
    section: 'systems',
    question: 'Does your school have a confidential reporting mechanism for bullying, harassment, or personal distress?',
    shortTitle: 'Confidential reporting missing',
    regulatoryRef: 'SC Guideline VIII',
    legalRisk: 'Without confidential channels, schools face elevated exposure when student concerns escalate.',
    zengardenCovers: 'Zengarden provides confidential support pathways and secure help requests.',
  },
  {
    id: 'Q9',
    order: 9,
    section: 'systems',
    question: 'Does your school run structured career counselling sessions conducted by qualified professionals and documented properly?',
    shortTitle: 'Structured career counselling absent',
    regulatoryRef: 'SC Guideline XII · CBSE TRG-03/2026',
    legalRisk: 'Ad hoc career talks without structure and records leave clear compliance gaps.',
    zengardenCovers: 'Zengarden supports structured mentor sessions and assessment-led pathway guidance.',
  },
  {
    id: 'Q10',
    order: 10,
    section: 'students',
    question: 'Do students have access to validated personality or wellbeing assessments to surface support needs early?',
    shortTitle: 'Validated assessments unavailable',
    regulatoryRef: 'SC Guideline III · CBSE Structured Assessment Requirement',
    legalRisk: 'Informal check-ins alone do not satisfy structured assessment expectations.',
    zengardenCovers: 'Zengarden provides 16PF and Big Five assessments reviewed by qualified professionals.',
  },
  {
    id: 'Q11',
    order: 11,
    section: 'students',
    question: 'Does your school provide ongoing wellbeing literacy resources on emotional regulation, stress management, and self-awareness?',
    shortTitle: 'Wellbeing literacy not integrated',
    regulatoryRef: 'SC Guideline IX · CBSE TRG-03 Curriculum Integration',
    legalRisk: 'One-off sessions do not meet expectations for sustained student wellbeing education.',
    zengardenCovers: 'Zengarden includes always-on guided content and practical wellbeing modules.',
  },
  {
    id: 'Q12',
    order: 12,
    section: 'students',
    question: 'Are extracurricular activities (sports, arts, personality development) actively scheduled as part of student development?',
    shortTitle: 'Extracurricular support under-prioritised',
    regulatoryRef: 'SC Guideline XI',
    legalRisk: 'Overly academics-only systems are regularly highlighted in compliance reviews.',
    zengardenCovers: 'Zengarden insights help counsellors recommend strength-aligned extracurricular pathways.',
  },
  {
    id: 'Q13',
    order: 13,
    section: 'students',
    question: 'Does your school avoid public academic shaming, harmful ranking practices, and disproportionate pressure targets?',
    shortTitle: 'Harmful pressure practices present',
    regulatoryRef: 'SC Guideline IV',
    legalRisk: 'Documented high-pressure practices can increase legal and reputational risk for institutions.',
    zengardenCovers: 'Zengarden promotes strengths-based support and non-shaming counselling-led interventions.',
  },
  {
    id: 'Q14',
    order: 14,
    section: 'records',
    question: 'Does your school maintain anonymised records of interventions, referrals, and support sessions?',
    shortTitle: 'Intervention records incomplete',
    regulatoryRef: 'SC Guideline X',
    legalRisk: 'Without records, institutions cannot demonstrate due process during review or escalation.',
    zengardenCovers: 'Zengarden stores timestamped support records in a structured audit trail.',
  },
  {
    id: 'Q15',
    order: 15,
    section: 'records',
    question: 'Can your school generate an annual wellness report for regulators with interventions, referrals, and activity summaries?',
    shortTitle: 'Annual wellness report unavailable',
    regulatoryRef: 'SC Guideline X · CBSE TRG-03/2026',
    legalRisk: 'Manual, incomplete reporting often leads to delayed or non-compliant submissions.',
    zengardenCovers: 'Zengarden supports one-click compliance-oriented report generation workflows.',
  },
  {
    id: 'Q16',
    order: 16,
    section: 'records',
    question: 'Has your school prepared or submitted compliance documentation to the relevant authority this academic year?',
    shortTitle: 'Compliance submission not prepared',
    regulatoryRef: 'SC Mandate Enforcement · CBSE Affiliation Review',
    legalRisk: 'Schools without current-year documentation are at heightened inspection risk.',
    zengardenCovers: 'Zengarden preserves required evidence trails for timely documentation.',
  },
  {
    id: 'Q17',
    order: 17,
    section: 'training',
    question: 'Have all teaching and non-teaching staff completed wellbeing awareness training in the last six months?',
    shortTitle: 'Staff training cycle not current',
    regulatoryRef: 'SC Guideline VI',
    legalRisk: 'Outdated or missing staff training is a direct procedural gap under current expectations.',
    zengardenCovers: 'Zengarden training workflows can track completion and recurring training cycles.',
  },
  {
    id: 'Q18',
    order: 18,
    section: 'training',
    cbseOnly: true,
    question: 'Has your school completed CBSE mandatory CBP1 (Mental Health & Wellness) for the current academic year?',
    shortTitle: 'CBP1 completion pending',
    regulatoryRef: 'CBSE TRG-03/2026 · CBP1',
    legalRisk: 'Missing CBP1 completion is a direct CBSE compliance gap irrespective of other efforts.',
    zengardenCovers: 'Zengarden implementation support helps align staff capability-building with CBSE expectations.',
  },
  {
    id: 'Q19',
    order: 19,
    section: 'training',
    cbseOnly: true,
    question: 'Has your school completed CBSE mandatory CBP2 (Social-Emotional Learning) for the current academic year?',
    shortTitle: 'CBP2 completion pending',
    regulatoryRef: 'CBSE TRG-03/2026 · CBP2',
    legalRisk: 'CBP2 is independently mandatory; partial completion still leaves non-compliance risk.',
    zengardenCovers: 'Zengarden SEL-aligned content supports operational readiness for CBP2 expectations.',
  },
  {
    id: 'Q20',
    order: 20,
    section: 'training',
    question: 'Have staff been trained for sensitive, inclusive engagement with students from diverse and vulnerable backgrounds?',
    shortTitle: 'Inclusive engagement training missing',
    regulatoryRef: 'SC Guideline VII · CBSE TRG-03 Inclusive Conduct',
    legalRisk: 'Lack of inclusive engagement training raises risk during student grievance and compliance review.',
    zengardenCovers: 'Zengarden counselling frameworks include inclusive engagement practices for diverse student needs.',
  },
];

export function getVisibleQuestions(isCBSE: boolean): ComplianceQuestion[] {
  return COMPLIANCE_QUESTIONS.filter((q) => isCBSE || !q.cbseOnly);
}
