import { SECTION_LABELS } from './questions';
import { ANSWER_POINTS, computeComplianceResult } from './scoring';
import type { ComplianceAnswer, ComplianceResult, ComplianceSubmissionInput } from './types';

interface StoredSubmissionRow {
  id: string;
  created_at: string;
  contact_name: string;
  school_name: string;
  email: string;
  phone: string | null;
  is_cbse: boolean;
  overall_score: number;
  band: string;
  section_scores: unknown;
  answers: Array<{ question_id: string; answer: ComplianceAnswer; points: number }>;
  gaps: unknown;
}

function getEnv(name: string): string {
  const value = import.meta.env[name];
  if (!value) throw new Error(`Missing environment variable: ${name}`);
  return value;
}

function escapePdfText(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function makePdfBytes(pages: string[][]): Uint8Array {
  const objects: string[] = [];

  const addObj = (obj: string): number => {
    objects.push(obj);
    return objects.length;
  };

  const fontObj = addObj('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');

  const pageObjectIds: number[] = [];
  const contentObjectIds: number[] = [];

  for (const lines of pages) {
    const contentLines = ['BT', '/F1 11 Tf', '50 792 Td', '14 TL'];
    for (let i = 0; i < lines.length; i += 1) {
      const safe = escapePdfText(lines[i]);
      contentLines.push(`(${safe}) Tj`);
      if (i < lines.length - 1) contentLines.push('T*');
    }
    contentLines.push('ET');
    const contentStr = contentLines.join('\n');
    const contentObjId = addObj(`<< /Length ${contentStr.length} >>\nstream\n${contentStr}\nendstream`);
    contentObjectIds.push(contentObjId);

    const pageObjId = addObj('');
    pageObjectIds.push(pageObjId);
  }

  const kidsRef = pageObjectIds.map((id) => `${id} 0 R`).join(' ');
  const pagesObj = addObj(`<< /Type /Pages /Kids [ ${kidsRef} ] /Count ${pageObjectIds.length} >>`);

  for (let i = 0; i < pageObjectIds.length; i += 1) {
    objects[pageObjectIds[i] - 1] =
      `<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${fontObj} 0 R >> >> /Contents ${contentObjectIds[i]} 0 R >>`;
  }

  const catalogObj = addObj(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [0];
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i <= objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogObj} 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  return new TextEncoder().encode(pdf);
}

function chunkLines(lines: string[], linesPerPage = 46): string[][] {
  const pages: string[][] = [];
  for (let i = 0; i < lines.length; i += linesPerPage) {
    pages.push(lines.slice(i, i + linesPerPage));
  }
  return pages;
}

export function buildReportPdf(
  submission: Pick<ComplianceSubmissionInput, 'contactName' | 'schoolName' | 'isCBSE'>,
  result: ComplianceResult,
  generatedAt: string,
): Uint8Array {
  const lines: string[] = [];

  lines.push('ZENGARDEN COMPLIANCE GAP REPORT');
  lines.push('');
  lines.push(`School: ${submission.schoolName}`);
  lines.push(`Contact: ${submission.contactName}`);
  lines.push(`Date: ${generatedAt}`);
  lines.push(`Score: ${result.overallScore}%`);
  lines.push(`Band: ${result.band.toUpperCase()}`);
  lines.push(`Path: ${submission.isCBSE ? 'CBSE' : 'NON-CBSE'}`);
  lines.push('Prepared by Zengarden - zengarden.co.in');
  lines.push('');
  lines.push('SECTION SCORES');
  for (const sec of result.sectionScores) {
    lines.push(`- ${SECTION_LABELS[sec.id]}: ${sec.score}% (${sec.points}/${sec.maxPoints})`);
  }
  lines.push('');
  lines.push('TOP COMPLIANCE GAPS');
  for (const gap of result.allGaps) {
    lines.push('');
    lines.push(`Gap: ${gap.shortTitle}`);
    lines.push(`Reference: ${gap.regulatoryRef}`);
    lines.push(`Risk: ${gap.legalRisk}`);
    lines.push(`Zengarden covers: ${gap.zengardenCovers}`);
  }
  lines.push('');
  lines.push('NEXT STEPS');
  lines.push('Book a 20-minute demo: https://calendly.com/aaddii091');
  lines.push('Contact: admin@zengarden.co.in | +91 7727052026');
  lines.push('This is a self-assessment tool. It is not a legal compliance certificate.');
  lines.push('Generated by Zengarden Compliance Checker - zengarden.co.in | This report is for awareness purposes only and does not constitute legal advice.');

  return makePdfBytes(chunkLines(lines));
}

function buildBandCopy(band: string): string {
  if (band === 'green') return "You're in good shape with minor gaps to close.";
  if (band === 'amber') return 'Your school has significant exposure that needs attention.';
  return 'Your school is currently non-compliant and at legal risk.';
}

export async function sendSubmissionEmail(
  submission: ComplianceSubmissionInput,
  result: ComplianceResult,
): Promise<void> {
  const apiKey = import.meta.env.RESEND_API_KEY;
  if (!apiKey) return;

  const topGaps = result.topGaps
    .map((g) => `<li><strong>${g.shortTitle}</strong> — ${g.regulatoryRef}</li>`)
    .join('');

  const html = `
    <p>Hi ${submission.contactName},</p>
    <p>Your school scored <strong>${result.overallScore}%</strong> on the Zengarden Compliance Check against SC Guidelines and CBSE requirements.</p>
    <p>Your compliance band: <strong>${buildBandCopy(result.band)}</strong></p>
    <p>Your top 3 gaps:</p>
    <ul>${topGaps || '<li>No major gaps identified.</li>'}</ul>
    <p>When you're ready to close these gaps, book a 20-minute call with our team.</p>
    <p><a href="https://calendly.com/aaddii091">Book a Demo</a></p>
    <p>The Zengarden Team<br/>admin@zengarden.co.in<br/>+91 7727052026</p>
  `;

  await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Zengarden Compliance Team <admin@zengarden.co.in>',
      to: [submission.email],
      subject: `Your school's compliance score - ${result.overallScore}% | ${submission.schoolName}`,
      html,
    }),
  });
}

function toStoredAnswers(answers: Record<string, ComplianceAnswer>) {
  return Object.entries(answers).map(([question_id, answer]) => ({
    question_id,
    answer,
    points: ANSWER_POINTS[answer],
  }));
}

async function supabaseFetch(path: string, init: RequestInit = {}): Promise<Response> {
  const supabaseUrl = getEnv('SUPABASE_URL');
  const serviceRole = getEnv('SUPABASE_SERVICE_ROLE_KEY');

  return fetch(`${supabaseUrl}${path}`, {
    ...init,
    headers: {
      apikey: serviceRole,
      Authorization: `Bearer ${serviceRole}`,
      'Content-Type': 'application/json',
      ...(init.headers || {}),
    },
  });
}

export async function saveSubmission(input: ComplianceSubmissionInput, result: ComplianceResult): Promise<StoredSubmissionRow> {
  const payload = {
    contact_name: input.contactName,
    school_name: input.schoolName,
    email: input.email,
    phone: input.phone || null,
    is_cbse: input.isCBSE,
    overall_score: result.overallScore,
    band: result.band,
    section_scores: result.sectionScores,
    answers: toStoredAnswers(input.answers),
    gaps: result.allGaps,
  };

  const response = await supabaseFetch('/rest/v1/compliance_submissions?select=*', {
    method: 'POST',
    headers: {
      Prefer: 'return=representation',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Failed to store submission: ${details}`);
  }

  const rows = (await response.json()) as StoredSubmissionRow[];
  return rows[0];
}

export async function getSubmissionById(id: string): Promise<StoredSubmissionRow | null> {
  const response = await supabaseFetch(`/rest/v1/compliance_submissions?id=eq.${encodeURIComponent(id)}&select=*&limit=1`);

  if (!response.ok) return null;
  const rows = (await response.json()) as StoredSubmissionRow[];
  return rows[0] ?? null;
}

export async function getAllSubmissions(): Promise<StoredSubmissionRow[]> {
  const response = await supabaseFetch('/rest/v1/compliance_submissions?select=*&order=created_at.desc');
  if (!response.ok) {
    const details = await response.text();
    throw new Error(`Failed to fetch submissions: ${details}`);
  }
  return (await response.json()) as StoredSubmissionRow[];
}

export function recomputeResultFromStored(row: StoredSubmissionRow): ComplianceResult {
  const answerMap: Record<string, ComplianceAnswer> = {};
  for (const entry of row.answers || []) {
    answerMap[entry.question_id] = entry.answer;
  }
  return computeComplianceResult(row.is_cbse, answerMap);
}

export function rowToCsv(rows: StoredSubmissionRow[]): string {
  const header = [
    'id',
    'created_at',
    'contact_name',
    'school_name',
    'email',
    'phone',
    'is_cbse',
    'overall_score',
    'band',
  ];

  const escape = (value: unknown) => {
    const raw = String(value ?? '');
    return `"${raw.replace(/"/g, '""')}"`;
  };

  const body = rows.map((r) => [
    r.id,
    r.created_at,
    r.contact_name,
    r.school_name,
    r.email,
    r.phone ?? '',
    r.is_cbse,
    r.overall_score,
    r.band,
  ].map(escape).join(','));

  return [header.join(','), ...body].join('\n');
}
